### ISSUE TITLE
Alpine based container

### ISSUE THREAD

**Issue by petersonnek** [cloudworkz/kafka-minion#1]
This more of a personal preference. The Scratch base image is nice and keeps thinks small. At the expense of a few more MB an Alpine Go image base may be a better choice to provide a bit of flexibility for people using your published container, specifically because a shell is included. In our case, we use Hashicorp Vault for secrets and leverage side car containers, volumes, and scripts to inject the secrets into the container. In order to pull this off I'll need to do some type of container rebuild rather than a command override in Helm.

One option would be change the existing dockerfile to use an Alpine base image. Another option may be to publish a separate image based on Alpine.

Thanks for the project and consideration!

**Comment by weeco** [comment]
Hey Peter,
thanks for describing your use case and submitting this issue. I'll definetely try to help you, as I know it is annoying to take over the responsibility of building the docker images for each release.

I believe the best option would be to provide images in both versions (alpine and scratch) so everyone can choose the preferred version. I'll take a look to see what's the best way to realize this with quay.

**Comment by weeco** [comment]
I couldn't find a handy solution to create both images for every release. Until I did we can use an alpine based image for the runtime. The images should still be fairly small.

If you need the alpine image you can pull an image from Master (which is currently untested) or wait for the new release.
