### ISSUE TITLE
Can support kafka 0.10.0.0 version?

### ISSUE THREAD

**Issue by chaplinthink** [cloudworkz/kafka-minion#11]
Hi ,  i want to ask  if  kafka-minion  support kafka 0.10.0.0?

**Comment by weeco** [comment]
Hi, no Kafka 0.10 is not supported, see Feature list:

> Supports Kafka 0.11.0.2 - 2.2.x (last updated 16th Jun 2019)

This is neither planned to add, I'm sorry.
