### ISSUE TITLE
build info

### ISSUE THREAD

**Issue by pvyaka01** [cloudworkz/kafka-minion#13]
Is this k8s specific or can we use as standalone exporter? If we can, how do we build it, just with go? Also, is there a way to display the consumers of the topics like we can with kafka commands?

Thanks!

**Comment by weeco** [comment]
Hi, you can deploy Kafka Minion on any platform. See the dockerfile to see how to build it, that's very straightforward.

Yes you can also list the consumers of the topics (see kafka minion ops dashboard). If you are looking for a CLI interface, I would recommend you to take a look at https://github.com/birdayz/kaf
