### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by pvyaka01** [cloudworkz/kafka-minion#14]
Thanks for your earlier reply. I tried to build but ran into this issue:

../go/pkg/mod/github.com/!shopify/sarama@v1.22.1/compress.go:9:2: unknown import path "github.com/eapache/go-xerial-snappy": git -c core.autocrlf=input -c core.eol=lf archive --format=zip --prefix=prefix/ 776d5712da21bc4762676d614db1d8a64f4238b0 in

Admittedly, i'm not well versed with go but it failed with the above error. Any help would be greatly appreciated!

**Comment by pvyaka01** [comment]
After cleaning up and trying again, was able to build. However, running into issues - it is not able to connect to kafka brokers. I've a kafka_exporter on the same server which is running fine. Here's what I did:
1. TELEMETRY_HOST=localhost
2. TELEMETRY_PORT=9310 (default is 8080 but that didn't work so changed it)
3. KAFKA_BROKERS=<list of brokers:9092> (comma separated list of 3 brokers)
4. Started ./kafka-minion

 {"level":"info","msg":"Starting kafka minion version1.0.0","time":"2019-08-15T15:22:57Z"}
{"level":"debug","msg":"Sarama client config has been created successfully","time":"2019-08-15T15:22:57Z"}
{"address":"<server1>:9092,<server2>:9092,<server3>:9092","level":"info","module":"cluster","msg":"connecting to kafka cluster","time":"2019-08-15T15:22:57Z"}

And errors out with this:
{"address":"<server1>:9092","level":"panic","module":"cluster","msg":"failed to start client","reason":"kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","time":"2019-08-15T14:58:58Z"}
panic: (*logrus.Entry) (0x9b1b80,0xc0001031f0)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc00006a3c0, 0xc00016afc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

The server is reachable (and kafka_exporter returns the metrics)
telnet <server> 9092
Trying 10.253.144.5...
Connected to <server>
Escape character is '^]'.


Thanks for the help

**Comment by weeco** [comment]
What does your `KAFKA_BROKERS` environment variable value look like? In the log you can see it has got this for the address which definetely looks wrong:

```
":9092,:9092,<server3:9092"
```

**Comment by pvyaka01** [comment]
sorry, I took the actual server list out. The server list is correct. Log look likes this:
{"level":"info","msg":"Starting kafka minion version1.0.0","time":"2019-08-15T15:33:48Z"}
{"level":"debug","msg":"Sarama client config has been created successfully","time":"2019-08-15T15:33:48Z"}
{"address":"<server1>:9092, <server2>:9092, <server3>:9092","level":"info","module":"cluster","msg":"connecting to kafka cluster","time":"2019-08-15T15:33:48Z"}
{"address":"<server1>:9092, <server2>:9092, <server3>:9092","level":"panic","module":"cluster","msg":"failed to start client","reason":"kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","time":"2019-08-15T15:35:49Z"}
panic: (*logrus.Entry) (0x90d240,0xc00018c150)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000623c0, 0xc000184630, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/<username>/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2cf
github.com/sirupsen/logrus.(*Entry).Log(0xc00018c0e0, 0xc000000000, 0xc00013f860, 0x1, 0x1)
        /home/<username>/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xc8

**Comment by weeco** [comment]
Unless you redacted the address again this does still look wrong. I don't believe sarama understands `:9092` as `localhost:9092` if it was that what you were trying. Also these connection errors directly come from Sarama, so I'd definetely investigate whether your provided address string was wrong or whether the Cluster is actually accessible

**Comment by pvyaka01** [comment]
i'm leaving out the actual server names for security reasons but here's how the env looks:
 echo $KAFKA_BROKERS
<server1-fqdn>:9092, <server2-fqdn>:9092, <server3-fqdn>:9092

Comma separated list of brokers.

The same servers are scraped successfully by kafka_exporter (which is not as comprehensive as this one)

Again, thanks for taking a look at this!

**Comment by pvyaka01** [comment]
Sorry, I think adding "<>" is not working so this time, I took those chars out. :)

**Comment by weeco** [comment]
I am sorry I have no clue why this would fail as this is only being parsed as string array and then it's passed to sarama which tries to connect to the Kafka cluster.

You redacted the original input and your previous post indicate that you put a space after your commas. Maybe that's something you want to take a look at again? Other than that I don't have any ideas. I could probably change the log output so that it prints the parsed kafka brokers (string slice) instead of the raw input

**Comment by weeco** [comment]
@pvyaka01 Were you able to resolve the issue?

**Comment by pvyaka01** [comment]
No, tried a couple of times and gave up. Perhaps some extra logging might help.

Thanks
On Saturday, September 14, 2019 Weeco <reply@reply.github.com> wrote:

@pvyaka01 Were you able to resolve the issue?
