### ISSUE TITLE
Add informational metrics

### ISSUE THREAD

**Issue by mindw** [cloudworkz/kafka-minion#16]
Thank you for making this work public!

While working with other prometheus exporters I've found the advice to add a `*_build_info` metrics very useful:
https://www.robustperception.io/exposing-the-software-version-to-prometheus

In addition, any stable Kafka metadata (`kafka_cluster_info`?) would be welcome as well!

**Comment by weeco** [comment]
Can you describe a usecase where it would be helpful to have Kafka Minion's build version part of the prometheus metrics?

**Comment by mindw** [comment]
Here are two on top of my head:
1. allow to get the version without access to the k8s manifests or deployments.
2. very useful with multiple deployments - increases with every new kafka-minion version. Makes operators life easier.
