### ISSUE TITLE
Failed to get config/highwater/lowwater from broker

### ISSUE THREAD

**Issue by Xaelias** [cloudworkz/kafka-minion#2]
Hi there!
Trying out your exporter (because I'm too lazy to rewrite the one I have to natively export metrics for prometheus :-D)
And I'm seeing the following errors:
```
{"error":"EOF","level":"warning","module":"cluster","msg":"failed to get describe configs response","time":"2019-06-10T13:01:20Z"}
{"broker_id":1,"error":"EOF","level":"error","module":"cluster","msg":"failed to fetch high watermarks from broker","time":"2019-06-10T13:01:20Z"}
{"broker_id":1,"error":"kafka: broker not connected","level":"error","module":"cluster","msg":"failed to fetch low watermarks from broker","time":"2019-06-10T13:01:20Z"}
```
This is by just running the plain go binary on a regular machine. No docker, no k8s, ...
`TELEMETRY_HOST=127.0.0.1 TELEMETRY_PORT=9111 VERSION=0.1.3 EXPORTER_METRICS_PREFIX=kafka_offsets KAFKA_BROKERS=localhost:9092 ./kafka-minion`
What am I doing wrong?

Thanks!

**Comment by weeco** [comment]
Hey, what Kafka version are you running?

**Comment by Xaelias** [comment]
0.10.1.1
You are not allowed to make any derogatory comment about how old this is :-D

**Comment by Xaelias** [comment]
I'm also getting `{"level":"info","msg":"Offets topic has not yet been consumed until the end","time":"2019-06-10T13:56:20Z"}` when I try to curl the `/metrics` endpoint. I assume it's a side effect of these errors I'm seeing.
Because the cluster I'm running against is not seeing a whole lot of traffic these days. the `__consumer_offsets` topic is only ~160MB on disk, and `kakfa-minion` has been running for ~40min.

**Comment by Xaelias** [comment]
Oh and if that helps, it complains about every brokers in that cluster, one after the other. Not just 1.

**Comment by weeco** [comment]
There is a chance that 0.11 is the minimum required version, but I'd need to test it. Additionally I could improve kafka minion so that it would print a more accurate error version if you try to use an unsupported kafka version

**Comment by weeco** [comment]
The minimum requirement is v0.11.0.2. I updated the Readme accordingly. I am sorry.
