### ISSUE TITLE
Kafka-minion keeps fetching from __consumer_offsets, causing high CPU load on a single broker

### ISSUE THREAD

**Issue by ChrisBlom** [cloudworkz/kafka-minion#21]
Hi, we have been running kafka minion on several environments for some time,
using this setup:

Server 1: running kafka broker 1 and kafka-minion
Server 2: running kafka broker 2
Server 3: running kafka broker 3 

On one environment we noticed the following:

- Server 1 had increased CPU and high network in
- Server 2 had high CPU (99%) and high network out 
- Kafka broker 2 had increased fetch requests for the __consumer_offsets topic

We are pretty sure that kafka minion was causing this, as the problems immediately stopped when we stopped kafka-minion, and came back when we started kafka-minion again.

We suspect that for some reason kafka-minion keeps fetching from __consumer_offsets, overloading broker 2.

This is the kafka minion log:

```
Oct 01 14:59:13 localhost kafka-minion[477]: {"level":"info","msg":"Starting kafka minion version1.0.0","time":"2019-10-01T14:59:13Z"}
Oct 01 14:59:13 localhost kafka-minion[477]: {"address":kafka-zookeeper01.internal:9092,kafka-zookeeper02.internal:9092,kafka-zookeeper03.internal:9092","level":"info","module":"cluster","msg":"connecting to kafka cluster"
Oct 01 14:59:14 kafka-zookeeper01 kafka-minion[477]: {"address":kafka-zookeeper01.internal:9092,kafka-zookeeper02.internal:9092,kafka-zookeeper03.internal:9092","level":"info","module":"cluster","msg":"successfully
Oct 01 14:59:14 kafka-zookeeper01 kafka-minion[477]: {"address":kafka-zookeeper01.internal:9092,kafka-zookeeper02.internal:9092,kafka-zookeeper03.internal:9092","level":"info","module":"offset_consumer","msg":"Conne
Oct 01 14:59:14 kafka-zookeeper01 kafka-minion[477]: {"error":"no brokers available","level":"warning","module":"cluster","msg":"failed to get active broker to refresh topic config","time":"2019-10-01T14:59:14Z"}
Oct 01 14:59:14 kafka-zookeeper01 kafka-minion[477]: {"address":kafka-zookeeper01.internal:9092,kafka-zookeeper02.internal:9092,kafka-zookeeper03.internal:9092","level":"info","module":"offset_consumer","msg":"Succe
Oct 01 14:59:14 kafka-zookeeper01 kafka-minion[477]: {"count":50,"level":"info","msg":"Starting '50' partition consumers","time":"2019-10-01T14:59:14Z","topic":"__consumer_offsets"}
Oct 01 14:59:14 kafka-zookeeper01 kafka-minion[477]: {"count":50,"level":"info","msg":"Spawned all consumers","time":"2019-10-01T14:59:14Z","topic":"__consumer_offsets"}
Oct 01 14:59:14 kafka-zookeeper01 kafka-minion[477]: {"level":"info","msg":"Listening on: '0.0.0.0:7070","time":"2019-10-01T14:59:14Z"}
Oct 01 14:59:14 kafka-zookeeper01 kafka-minion[477]: {"level":"info","module":"storage","msg":"Registered 50 __consumer_offsets partitions which have to be consumed before metrics can be exposed","time":"2019-10-01T14:59:14Z"}
Oct 01 15:02:14 kafka-zookeeper01 kafka-minion[477]: {"error":"EOF","level":"warning","module":"cluster","msg":"failed to get metadata","time":"2019-10-01T15:02:14Z"}
Oct 01 15:03:14 kafka-zookeeper01 kafka-minion[477]: {"error":"write tcp 10.164.0.23:41508-\u003e10.164.0.24:9092: write: broken pipe","level":"warning","module":"cluster","msg":"failed to get metadata","time":"2019-10-01T15:03:14Z"}
Oct 01 15:03:24 kafka-zookeeper01 kafka-minion[477]: {"broker_id":2,"error":"write tcp 10.164.0.23:41508-\u003e10.164.0.24:9092: write: broken pipe","level":"error","module":"cluster","msg":"failed to fetch high watermarks from broker","time":"2019-10-01T15:03:24Z"}
Oct 01 15:03:24 kafka-zookeeper01 kafka-minion[477]: {"broker_id":2,"error":"kafka: broker not connected","level":"error","module":"cluster","msg":"failed to fetch low watermarks from broker","time":"2019-10-01T15:03:24Z"}
```

Despite what these logs suggest, this cluster is operational, all nodes can communicate with each other.

Do you have any idea what could cause this problem, and what can we do to fix it?

**Comment by weeco** [comment]
Hi,
Kafka Minion tries to consume as many consumer offsets messages as possible. If you don't limit the CPU usage or throttle it otherwise this can overload your Kafka cluster which seems to be the case here.

These error logs shouldn't be a showstopper, as it periodically tries to fetch metadata/watermarks from all brokers.

**Comment by ChrisBlom** [comment]
Hi, thanks fo the quick reply.
Kafka-minion never finishes consuming the __consumer_offsets in this environment, even after running for days.
I'll try to throttle the CPU usage and see if that helps

**Comment by weeco** [comment]
Kafka minion has some internal metrics which indicate how many messages it consumes per second. You may want to create a dashboard for that

**Comment by ChrisBlom** [comment]
I've throttled the cpu usage, it seems to help a bit, but the CPU usage of kafka server 2 is still pretty high. I've created a dashboard for the metrics, I'll report back when I have more info.

**Comment by ChrisBlom** [comment]
Hi, I have throttled the cpu of kafka-minion, but the problems persist, athough the cpu load on kafka 2 is a little less. Kafka-minion still fails to consume the offsets topic after ~16 hours.

Attached is a screenshot of the collected metrics:

![kafka-minion-high-cpu](https://user-images.githubusercontent.com/1045624/66107365-60addf80-e5c0-11e9-89c6-256d98b35865.png)

**Comment by weeco** [comment]
The dashboard indicates that kafka minion keeps processing offset commit messages. Is it still catching up with the offsets or is it processing the messages at the same rate as offset commits flow into the topic?

My experience is that it can consume 100k messages / sec with 2 cores. Accordingly it takes only a few minutes to process all offset commits in my kafka clusters.

**Comment by weeco** [comment]
I'll close this issue because I think in the end it boils down to https://github.com/cloudworkz/kafka-minion/issues/15
