### ISSUE TITLE
Add support for Kerberos Auth

### ISSUE THREAD

**Issue by jim-mclean** [cloudworkz/kafka-minion#23]
Looks like this project does not allow for Kerberos based authentication.  Digging a little deep it appears that the Sarma Kafka Client does:  https://github.com/Shopify/sarama/blob/master/gssapi_kerberos.go

Can someone the ability to config Kafka connections to use Kerb Auth?

**Comment by weeco** [comment]
@jim-mclean I filed PR #30 , can you review it and see if there are any config options missing? I am not very familiar with Kerberos and I don't have a cluster to test Kerberos against.
