### ISSUE TITLE
Only get an Empty reply from server

### ISSUE THREAD

**Issue by robdt** [cloudworkz/kafka-minion#24]
Hi, I think I have everything configured correctly. I ran with debug and the debugging output looked like I would have expected. But when I just try to curl the metrics REST API it sits for a while, then it give me an "Empty reply from server" and subsequently refuses any attempts at connections.

```
~/robt/kafka-lag/kafka-minion > curl localhost:8080/readycheck
Offsets topic has not been consumed yet
~/robt/kafka-lag/kafka-minion > curl localhost:8080/readycheck
Ready~/robt/kafka-lag/kafka-minion > curl localhost:8080/healthcheck
Healthy~/robt/kafka-lag/kafka-minion > curl localhost:8080/metrics
curl: (52) Empty reply from server
~/robt/kafka-lag/kafka-minion > curl localhost:8080/metrics
curl: (7) Failed to connect to localhost port 8080: Connection refused
~/robt/kafka-lag/kafka-minion > curl localhost:8080/healthcheck
curl: (7) Failed to connect to localhost port 8080: Connection refused
```
The container (and I am assuming the application) dies around that time, and there is nothing of interest in the log:

```
~/robt/kafka-lag > docker container logs kafka-minion
{"level":"info","msg":"Starting kafka minion version1.0.0","time":"2019-11-12T19:32:37Z"}
{"address":"<Kafka IP>:9092","level":"info","module":"cluster","msg":"connecting to kafka cluster","time":"2019-11-12T19:32:37Z"}
{"address":"<Kafka IP>:9092","level":"info","module":"cluster","msg":"successfully connected to kafka cluster","time":"2019-11-12T19:32:38Z"}
{"address":"<Kafka IP>:9092","level":"info","module":"offset_consumer","msg":"Connecting to kafka cluster","time":"2019-11-12T19:32:38Z"}
{"error":"no brokers available","level":"warning","module":"cluster","msg":"failed to get active broker to refresh topic config","time":"2019-11-12T19:32:38Z"}
{"address":"<Kafka IP>:9092","level":"info","module":"offset_consumer","msg":"Successfully connected to kafka cluster","time":"2019-11-12T19:32:38Z"}
{"count":50,"level":"info","msg":"Starting '50' partition consumers","time":"2019-11-12T19:32:38Z","topic":"__consumer_offsets"}
{"count":50,"level":"info","msg":"Spawned all consumers","time":"2019-11-12T19:32:38Z","topic":"__consumer_offsets"}
{"level":"info","msg":"Listening on: '0.0.0.0:8080","time":"2019-11-12T19:32:38Z"}
{"level":"info","module":"storage","msg":"Registered 50 __consumer_offsets partitions which have to be consumed before metrics can be exposed","time":"2019-11-12T19:32:38Z"}
{"level":"info","msg":"Offets topic has not yet been consumed until the end","time":"2019-11-12T19:32:44Z"}
{"level":"info","msg":"Offets topic has not yet been consumed until the end","time":"2019-11-12T19:32:51Z"}
{"level":"info","msg":"Offets topic has not yet been consumed until the end","time":"2019-11-12T19:32:54Z"}
{"level":"info","msg":"Offets topic has not yet been consumed until the end","time":"2019-11-12T19:33:04Z"}
{"level":"info","msg":"Offets topic has not yet been consumed until the end","time":"2019-11-12T19:33:14Z"}
{"level":"info","msg":"Offets topic has not yet been consumed until the end","time":"2019-11-12T19:33:24Z"}
{"level":"info","msg":"Offets topic has not yet been consumed until the end","time":"2019-11-12T19:33:34Z"}
{"level":"info","module":"storage","msg":"Offset topic has been consumed","time":"2019-11-12T19:36:48Z"}
~/robt/kafka-lag > 
```

I had to run with INFO, because when I ran with DEBUG it took over 2 hours and still hadn't acquired the offsets topic.

Please let me know if you have any insight into the problem, if there is any additional information I can share, or if there is anything else that I can try.

Thanks for making this tool! I am really hoping to get it working, it looks like it is going to be great to use.

**Comment by weeco** [comment]
Hey,
I think the /metrics endpoint should never return an empty reply. Even if it has not yet consumed the offsets topic the service would just expose the default metrics (like number of goroutines).

Looking at the provided logs everything looks absolutely fine (btw you may want to redact the hostnames). I don't see why switching the loglevel would have an impact, but the described issue seems to be related to: https://github.com/cloudworkz/kafka-minion/issues/15 . This seems to be a thing ,but I were not able to replicate that behaviour, even though I use it for several Kafka Clusters and some of them have very different configurations and workloads. Therefore it's kinda hard for me to figure out the cause. If you can reproduce the problem and have the chance to run the Go service with a debugger attached let me know.

The debug logs should however indicate what partition is not yet processed until the end.

**Comment by robdt** [comment]
Thank you for your response.

I have done more investigation after posting. I think that the switching of the log level didn't necessarily impact the problem, as much as it made things run slower. I am able to consume the offsets topic in minutes (might be tens of minutes) but when I run with debug on, I can run for 12+ hours and it still doesn't consume the offset topic.

I was able to get it to work once, and it took an incredibly long time to get the response back from the curl. I think this might be an issue with how the size of the kafka deployment I a trying to measure. It hasn't worked since that once, so it should be possible to get this to occur with the debugger attached. I found some instructions on running the debugger in the container, but I am somewhat unfamiliar with Go, so if you had a link to some instructions or tools to run the debugger, it would be greatly appreciated.

I will work on getting information from the debugger and update with it once I have it. Thanks again.

**Comment by robdt** [comment]
I was unable to get any information from the debugging. It looks like it was dying quietly inside of the internal prometheus.

Either way, I was able to solve the issue by increasing the amount of memory and swap allocated to the container. That seems to have fixed my issue. Thanks again for your attention to this.
