### ISSUE TITLE
Configuration without docker

### ISSUE THREAD

**Issue by bj9306** [cloudworkz/kafka-minion#25]
is it possible to configure kafka-minion without docker?

**Comment by weeco** [comment]
You can just compile it to a binary and start it by passing the arguments into it.

**Comment by bj9306** [comment]
what is the format to manually pass variable?

./kafka-minion --version=1.0.0
{"level":"fatal","msg":"Error parsing env vars into opts. required key VERSION missing value","time":"2019-12-09T13:59:15-08:00"}

./kafka-minion --VERSION 1.0.0
{"level":"fatal","msg":"Error parsing env vars into opts. required key VERSION missing value","time":"2019-12-09T14:00:28-08:00"}

**Comment by weeco** [comment]
I am sorry I was wrong with the arguments, this project expects environment variables to be injected rather than passing arguments into it.
