### ISSUE TITLE
unable to load root ca file (ca.pem

### ISSUE THREAD

**Issue by gvajpeyi** [cloudworkz/kafka-minion#49]
afka_minion[20856]: {"error":"open /home/gaurav_vajpeyi/newprod/ca.pem: no such file or directory","level":"panic","msg":"failed to load ca file","time":"2020-07-02T18:17:36Z"}

file is there still it unable to read or load self sign cert

**Comment by weeco** [comment]
There's nothing we could do about it. I think you should make sure that a file under that path actually exists.

See this call: https://github.com/cloudworkz/kafka-minion/blob/532f86415520f562a965c7752363b94c0e7631ac/kafka/connection_helper.go#L36

**Comment by gvajpeyi** [comment]
Thanks for reply ..
I am using into binary and passing the path in env
Environment="KAFKA_TLS_CA_FILE_PATH=/home/gaurav_vajpeyi/newprod/ca.pem"

ls -ltr /home/gaurav_vajpeyi/newprod/ca.pem 
-rw-r--r-- 1 root root 855 Mar  8  2019 /home/gaurav_vajpeyi/newprod/ca.pem

Path exists not sure go lang able to read in this way 
I have no idea about go lang and how to describe the path in the binary

**Comment by godwhoa** [comment]
@gvajpeyi I think you also need to set `KAFKA_TLS_ENABLED=true`
https://github.com/cloudworkz/kafka-minion/blob/07954f3407591d68ba8edae15dee6716c2ad687d/options/options.go#L54

**Comment by gvajpeyi** [comment]
I found the issue it looks like my ca file name is same ca.pem due to which it not able to understand 

now it no giving that error but  move to new error 

client/metadata got error from broker -1 while fetching metadata: local error: tls: unexpe
cted message\n","source":"sarama","time":"2020-07-03T10:38:53Z"}

**Comment by gvajpeyi** [comment]
2-way auth ssl auth is not working 

if I disable SSL auth to none it connects with my certs 

this also works but connection_helper.go always gives me  error failed to connect to localhost/0:0:0:0:0:0:0:1 on broker side and here on Kafka minion side tls error 

please check 
[gossl.txt](https://github.com/cloudworkz/kafka-minion/files/4871424/gossl.txt)

**Comment by gvajpeyi** [comment]
Hey

I update my case can any one help me please

**Comment by gvajpeyi** [comment]
All issue has been resolved

**Comment by weeco** [comment]
@gvajpeyi Do you mind sharing what was wrong in case someone runs into the same issues?

**Comment by gvajpeyi** [comment]
sure...

So I was using binary to run with Linux service and passing all env value there
I copy the repo into my home dir and go root dir is /use/bin/local where I put my binary file to run via Linux service.
So the issue which I facing is when I pass SSL cert path as an (/home/$username/ssl/*certs ) is not able to find but when I put these certs into same /usr/bin/local/ssl dir env variable able to read those certs 
Not sure why it happens but this is the way it works for me
