### ISSUE TITLE
Exclude stale consumers

### ISSUE THREAD

**Issue by smlgbl** [cloudworkz/kafka-minion#5]
Is there a way to exclude stale consumers?
I guess you're consuming the __consumer_offsets and keep the data, even though some of the consumer group-to-topic mappings may be old.

My example: we have some consumer groups where we changed the topic they consume from, e. g. the consumerGroup-1 consumed firstTopic, but now only consumes from secondTopic - hence it has a huge lag for firstTopic. But I'm not interested in that, because it hasn't consumed that topic in days/weeks...

Can I configure somehow after what time a stale consumer gets dropped from reporting metrics?
Or can I configure kafka-minion to not read the complete __consumer_offsets topic, but only start reading the latest messages?

**Comment by weeco** [comment]
Kafka Minion tries to report exactly what the Kafka Broker stores as consumer group lag. These consumer offsets do not get reported anymore when there's a Tombstone produced for a specific consumer-group:topic:lag combined key on the `__consumer_offsets` topic. When this happens this also means the consumer group offsets have expired on that partition.

So as far as I understood you'd like to have a feature where Kafka Minion drops the consumer group information before the consumer group has actually expired? If this is the case it wouldn't help you if Kafka Minion consumes the topic from latest (additionally this has a couple other downsides).

**Comment by smlgbl** [comment]
I just thought of a possible solution, but don't know how to accomplish this in Grafana/PromQL:

Take all groups and topics from the metric "kafka_minion_group_topic_lag", but only those where the metric "kafka_minion_group_topic_partition_commit_count" has values greater than 1 (or 2?)

**Comment by smlgbl** [comment]
@weeco You're fast!
What you're saying sounds reasonable and should be the correct way. It's not what I'm seeing, though .... unless my consumer group is still active for that topic.

**Comment by weeco** [comment]
We've had a couple similiar cases here as well where we thought the consumer group must have been expired, but it was still active.

When we checked the consumer groups with one of the kafka shells, it was confirmed that Kafka Minion was right - the group for the specific partition was still active. That does not mean that Kafka Minion can not be wrong in your case, but please first check with another tool if these offsets have actually expired.

Yes the last commit timestamps are epoch milliseconds which means your provided timestamp resolves to 30th Aug 2018. Unless you are using very high offset retention times this offset should have been expired. But once again we saw on our clusters a similar behaviour where such offsets have not yet expired (and I don't know why) and therefore Kafka Minion reported it correctly. Can you check that on your cluster as well?

**Regarding your use case:**

I believe it would be risky to hide all consumer groups which currently do not report offset commits, as you can quickly miss unhealthy (because dead) consumers.

**Comment by smlgbl** [comment]
Thanks for the hints, @weeco 
I checked with kafka-consumer-groups.sh, which gives the following output for one of the examples:
```
./kafka-consumer-groups --bootstrap-server broker-01.mydomain.com:9092 --group kafkaProcessor.prod --describe
Error: Consumer group 'kafkaProcessor.prod' does not exist.
```

Also, kafka minion shows, that the metric "kafka_minion_group_topic_partition_commit_count" only has a value of 1 or 2 for the partitions. I'm guessing those should be the tombstones, that were left behind?

**Comment by weeco** [comment]
Hmm hard to understand what has happened there. Tombstones will not increment the `partition_commit_count` counter and they have their own metric instead (which is not grouped by consumer group and partition though):

```go
	offsetCommitTombstone = prometheus.NewCounter(prometheus.CounterOpts{
		Name: prometheus.BuildFQName(internalMetricsName, "offset_consumer", "offset_commits_tombstones_read"),
		Help: "Number of read group offset commit tombstone messages",
	})
```

Did you check the kafka minion logs if there are any errors? If we receive a tombstone and something could not be properly decoded it's logged, see: https://github.com/cloudworkz/kafka-minion/blob/master/kafka/offset_consumer.go#L208-L235

If you have a chance to attach a debugger and run it with your kafka cluster, you could set conditional breakpoints which break when your expired consumer group had been decoded.

**Comment by smlgbl** [comment]
@weeco Sorry for the delay, I was travelling.
The only log output I see is
`{"level":"warning","module":"collector","msg":"could not calculate partition lag because low water mark is missing","partition":2,"time":"2019-07-02T08:23:58Z","topic":"blablabla"}`
I cannot attach a debugger to our kafka cluster at the moment.
If you come up with any other ideas I could try, please let me know :)
Thanks a lot!

**Comment by smlgbl** [comment]
@weeco No new ideas, but more cases where this is happening: it's always that a consumer group is still active, but for different topics. Right now I have no chance but to exclude the metrics on the dashboards, but this is quite cumbersome...

**Comment by weeco** [comment]
Hey @smlgbl , I missed your response 20 days ago - I am sorry for the late response. This indeed sounds cumbersome. To sum up our previous discussion and analysis we came to the conclusion that Kafka Minion either skips the Tombstone message, handles it improperly or there's no tombstone.

1. Could you take a look at the `__consumer_offsets` topic configuration and paste it here?

2. Can you nowadays provide more information to isolate the cause of the problem? E. g. does this happen for just one consumergroup/topic/partition? Do these offsets eventually disappear (basically just later than expected)?

If neither #1 or #2 help I'll go ahead and add debug log messages for received tombstones along with further instructions to figure it out.

**Comment by smlgbl** [comment]
1: https://pastebin.com/kvwkvumS
2. it happens for a couple of our consumer groups - most groups still exist, but consume a different topic than originally, yet the lag for the "old" topic is still reported. It also happens for at least one consumer group that simply doesn't exist anymore. So far I can't say they ever disappear, but I only paid attention when seeing the groups still around - I didn't keep track of others that worked as expected. But I also can't think of any off the top of my head.
BTW I just upgraded to v1.0.0 yesterday...

**Comment by weeco** [comment]
Good/Bad news: I am able to reliably reproduce the issue for one of my clusters/groups which I can use to debug against. It seems like we never get a tombstone for this consumer group. I have yet to figure out why this is the case and what else I should do to get notified about expired consumer group offsets.

**Comment by weeco** [comment]
To verify there's no bug in the code which processes the offset commit messages from the `__consumer_offsets` topic I ran the kafka-console-consumer with the `OffsetsMessageFormatter` option against the topic. Indeed there's simply no tombstone sent by Kafka for any of the partitions for that group.

```sh
kafka-console-consumer.sh --from-beginning --topic __consumer_offsets zookeeper.connect=${ZOO_HOST} --bootstrap-server="${KAFKA_HOST}"  --formatter "kafka.coordinator.group.GroupMetadataManager\$OffsetsMessageFormatter"
```

I have no explanation why Kafka sometimes doesn't send a tombstone even though the offsets are clearly expired. Apparently Kafka itself knows that this group / these offsets do not exist anymore.

One approach to workaround this issue would be looking at the `commitTimestamp` which we can read for all offset commits and check if this timestamp is older than the offset retention. If this is the case we'll evict the stored offset on our own, even if we haven't received a tombstone yet. Before I am going to proceed with this idea I'd like to spend some more time figuring out why Kafka doesn't send a tombstone for these groups / partitions.
