### ISSUE TITLE
Metrics Prefix Env Var

### ISSUE THREAD

**Issue by moserke** [cloudworkz/kafka-minion#6]
The Readme states the metrix prefix environment variable as `EXPORTER_METRICS_PREFIX`.  This is actually `METRICS_PREFIX`.  https://github.com/cloudworkz/kafka-minion/blob/master/options/options.go#L49

Not sure which should be updated...

**Comment by weeco** [comment]
`METRICS_PREFIX` is the correct one, I am sorry for the confusion. I'll update the Readme accordingly.

**Comment by moserke** [comment]
No problem!  Wasn't sure which you would want fixed (readme or code) so hence the issue.  Thanks for the quick note!
