### ISSUE TITLE
Question:  Startup Speed

### ISSUE THREAD

**Issue by moserke** [cloudworkz/kafka-minion#7]
For a really active cluster I am noticing long startup times, upwards of 10m.  This is due to having 50 partitions for the offsets topic so there are 50 partition consumers chewing through millions of records.

I was reading through the code some and I don't really see a good way of speeding this up, without a slight re-architecture so that partition consumers can be managed across the whole consumer group and then let multiple copies start up so that kafka balances the reading across the whole consumer group.  This or switch to using latest for the OffsetLatest on the consumer.  Also, shouldn't the consumer, if restarted, pick up where it left off?  Is it not persisting it's own offset? 

This is more just a "general" question of do you see the same issue?  Is there a way to tune this that I am missing?

This is not a huge deal as obviously once it's up and running it stays current.  The issue arises when running this is in a k8s cluster with ephemeral compute and the pod needs to move around, it would introduce large gaps/lag in the metrics reporting....

Anyway, this in no way is a ding on the tool, it's really great and glad I found it! (I was literally writing this exact thing when I stumbled upon it) So thanks for the great work on this!  It's really more a "have you had this issue?"

**Comment by weeco** [comment]
Hi,
we use Kafka Minion on mid sized clusters, with ~200 partitions on the `__consumer_offsets` topic and several millions of messages on it. We have similar startup/ready times here. This however is not a problem, nor a concern here even though we do send alerts based on the reported metrics. The simple reason for that is that we run multiple Kafka Minion instances (which report all the same metrics once they are ready).

Kafka Minion does not use Consumer Groups on purpose. To understand why, you need to understand what is being stored in the `__consumer_offsets` topic. By default this is a compacted topic, where offset commits from consumer group members are stored. Each message is an offset commit where the key is a combination of:

- Consumer Group Name
- PartitionID
- Topicname

Once an offset commit expires we'll receive a tombstone for that key. In return this means we always need to consume the topic from the beginning to understand which offsets haven't yet expired and therefore should be reported. Yes this could be done in parallel using consumer groups, but at the same this would introduce a lot more complexity and more room for failures as the data needs to be synced across instances.

We also have a cluster where we run Kafka Minion on preemptible nodes with hard anti affinities on nodes and pod disruption budget and we get gapless lag reports. The "offset commits processed" graph then looks like this:

<img width="1435" alt="Screenshot 2019-06-26 at 20 21 12" src="https://user-images.githubusercontent.com/23424570/60204840-04645280-9850-11e9-97a5-283b40e8458e.png">


**To answer your question though:**

While Kafka Minion is not horizontally scalable you can still scale it vertically to get faster startup times. With 2 CPU cores one Kafka Minion instance consumes 100k messages / second in our cluster. Assigning more cores should get you better throughput as well.

**Comment by moserke** [comment]
Ah that makes sense, and given that you can average the metrics out that brings you back to the "correct" number.  Not sure why that didn't compute in my brain.  ha  Of course I wanted a more "complicated" solution.  🤦‍♂ 

Thanks again for the info!
