### ISSUE TITLE
missing consumer groups and topics

### ISSUE THREAD

**Issue by cdenneen** [cloudworkz/kafka-minion#8]
I spun up 0.1.3 version of the container and only metrics I see exposed are:

```
kafka_minion_internal_offset_consumer_group_metadata_tombstones_read
kafka_minion_internal_offset_consumer_offset_commits_tombstones_read
kafka_minion_topic_partition_count
kafka_minion_topic_partition_high_water_mark
kafka_minion_topic_partition_low_water_mark
kafka_minion_topic_partition_message_count
```

besides `go_` and `process_` metrics

Any idea why the rest of them aren't showing?
Seems like Consumer Group metrics and Internal metrics are missing it's just:

"Topic/Partition metrics"

**Comment by weeco** [comment]
Hey, did you take a look at the logs? It takes a while until it consumed all the consumer_offsets topic and it should report on every `/metrics` request whether it's ready or not.

It does also print a logmessage once it's done. This can easily take a couple minutes, depending on the CPU usage you assign and the number of messages in your `__consumer_offsets` topic. I probably should add a sentence about it in the README 👍

**Comment by cdenneen** [comment]
Thanks for quick response:

```
{"count":3,"level":"info","msg":"Starting '3' partition consumers","time":"2019-06-26T21:50:43Z","topic":"__consumers_offsets"}
{"count":3,"level":"info","msg":"Spawned all consumers","time":"2019-06-26T21:50:43Z","topic":"__consumers_offsets"}
{"level":"info","module":"storage","msg":"Registered 3 __consumer_offsets partitions which have to be consumed before metrics can be exposed","time":"2019-06-26T21:50:43Z"}
{"level":"info","msg":"Listening on: '0.0.0.0:8080","time":"2019-06-26T21:50:43Z"}
{"level":"info","module":"storage","msg":"Offset topic has been consumed","time":"2019-06-26T21:50:48Z"}
```

**Comment by cdenneen** [comment]
@weeco thanks... see the typo... `__consumers__offsets`... changed to `__consumer_offsets` and it's working now.

Thanks again

**Comment by weeco** [comment]
Hmm this is odd, do you have any offset commits at all in your cluster?

**Side note:** Having just 3 __consumer_partitions is most likely not desirable for production clusters.

**Comment by weeco** [comment]
Thanks for checking again, you could also just omit the name as it defaults to this default topic name :-)

**Comment by cdenneen** [comment]
@weeco I'm really new to this. I have 3 nodes and I'm setting all topics to have 3 partitions as I create them. This is a MSK cluster. How would I set this up for production?

**Comment by weeco** [comment]
I don't know anything about Amazon MSK. It seems like they do not offer you to configure the number of partitions. Maybe they do scale it as you scale your topics' partitions?

**Comment by cdenneen** [comment]
`num.partitions = 1` is the default
So does that means it's 1 partition per node which is why it's 3? 
I probably should change this to 3 so it creates 3 per node so 9?
Thanks for the help
